<?php
	$dictionary['prefix_exception'] = array(
		'ber'	=> array('berabe','berada','beraga','berahi','berai','berak','berang','berani','berapa','berapi','berasa','berat','bercak','beres','beri','beriak','beribu','berita','berkas','berkat','bernas','berok','bersih','bersin','beruji','beruk','berupa'),
		'ter'	=> array('terang','terapi','teras','terasa','terasi','terbit','teri','teriak','terigu','terik','terima','terjal','terjun','terkam','termal','termin','termos','ternak','terong','teror','teroris','terpal','tertib','teruna','terus'),
		'me'	=> array('mebel','medali','medan','medang','mede','media','medial','median','medik','medio','medis','medium','medok','medula','medusa','mega','megah','megan','megar','mei','meja','mejam','mejeng','mek','mekar','melaka','melata','melati','melayu','melek','meler','meliat','melik','meliuk','melodi','melon','meluas','melucu','melulu','memang','memar','membeo','memble','memedi','memek','memicu','memo','memoar','memori','mempan','memper','memuai','memuat','memuja','memuji','menaik','menang','menara','menari','menata','mendem','mendoa','mendua','mendut','menipu','meniup','mens','mentah','mental','mentok','mentor','menu','menua','menuai','menuju','menyan','meong','mepet','meraba','merah','meraih','merak','meramu','merana','merasa','merata','merayu','mercon','mercu','merdu','mere','mereda','mereka','merem','merger','merguk','meriah','meriam','merias','merica','merjer','mertua','merugi','mesin','mesiu','mesjid','meski','mesra','mesti','mesum','meta','metal','metana','mete','meteor','metode','metrik','metris','metro','mewah','mewek'),
		'meng'	=> array('mengah','mengap','mengeh','menget','mengga','mengi','mengok','mengor','mengot'),
		'mem'	=> array('memacu','memadu','memaki','memaku','memang','memar','membal','membeo','memble','memedi','memek','memicu','memo','memoar','memori','mempan','memuai','memuat','memuja','memuji','memula'),
		'men'	=> array('menang','menara','menari','menata','mencak','mencit','mencok','mendem','mendoa','mendua','mendut','menhir','meni','menipu','menir','menit','meniup','menor','mens','mentah','mental','mentok','mentor','menu','menua','menuai','menuju','menyan'),
		'meny'	=> array('menyan'),
		'menge'	=> array('mengeh'),
		'di'	=> array('dia','diabetes','diad','diafragma','diagnosa','diagnosis','diagnostik','diagonal','diagram','diakonia','diakronis','dialek','dialektik','dialektika','dialektis','dialektologi','dialinguistik','dialog','dialogis','diam','diameter','dian','diare','dias','diaspora','diatonik','diatonis','didaktik','didaktis','didiang','didih','didik','diesel','diet','difabel','diferensial','diferensiasi','difluensi','difraksi','difteri','diftong','difusi','digdaya','digit','digital','digitalisasi','dikau','dikit','diklorida','dikotil','dikotomi','dikromat','dikromatik','diksa','diksi','diktat','diktator','dikte','diktum','dilema','dilematik','dimensi','dinamik','dinamika','dinamis','dinamisme','dinamit','dinamo','dinamometer','dinar','dinas','dinasti','dinding','dingin','dinosaurus','diode','dioksida','dioksin','dioptri','diorama','dipati','dipengapakan','diploma','diplomasi','diplomat','diplomatik','diplomatis','dipsomania','dirah','diraja','direksi','direktorat','direktori','direktur','dirgahayu','dirgantara','dirham','diri','dirigen','disel','disentri','disertasi','disinfektan','disinformasi','disinsentif','disintegrasi','disiplin','disko','diskon','diskontinu','diskontinuitas','diskonto','diskordans','diskorobik','diskotek','diskredit','diskresi','diskriminasi','diskriminatif','diskriminator','diskualifikasi','diskursus','diskusi','disleksia','disorder','disorientasi','dispensasi','dispenser','disposisi','disrupsi','distabilitas','distilasi','distilator','distorsi','distribusi','distributor','distrik','divergen','divergensi','diversitas','divestasi','dividen','divisi'),
		'peng'	=> array('pengabdi','pengacau','pengadaan','pengadu','pengagum','pengajar','pengaman','pengamat','pengamen','pengampu','penganan','penganti','pengantar','penganut','pengap','pengarah','pengarak','pengaruh','pengasah','pengasih','pengasuh','pengatur','pengawal','pengawas','pengawet','pengayom','pengebom','pengebor','pengecam','pengecap','pengecek','pengecer','pengecoh','pengecut','pengedar','pengembangan','pengemas','pengemis','pengenal','pengepul','pengerat','pengetik','penggagas','penggal','penggali','penggawa','penggede','penggeli','penggera','penggiat','penggila','penggoda','pengguna','penghela','penghias','penghobi','penghulu','penghuni','pengiba','pengibar','pengidap','pengikan','pengikat','pengikis','pengikut','pengirim','pengisap','pengisi','pengki','pengocok','pengojek','pengolah','pengolahan','penguasa','pengubah','penguin','penguji','pengukir','pengukur','pengulit','pengulun','pengunci','pengurus','pengusik','pengusir','pengutil','pengutip'),
		'pem'	=> array('pemaaf','pemabuk','pemacu','pemadat','pemahat','pemain','pemakai','pemalas','pemalsu','pemalu','pemanas','pemandu','pemanis','pemarah','pemasak','pemasar','pemasok','pembaca','pembawa','pembeda','pembeku','pembela','pembeli','pemberi','pembina','pembual','pembuat','pembuka','pemburu','pemecah','pemeluk','pemeran','pemeras','pemetik','pemicu','pemijat','pemikat','pemikir','pemikul','pemilih','pemilik','pemimpi','peminat','peminta','peminum','pemirsa','pemisah','pemitar','pemodal','pemogok','pemohon','pemoles','pempek','pemuat','pemuda','pemudah','pemudi','pemudik','pemugar','pemuja','pemuji','pemujur','pemuka','pemukat','pemukim','pemukul','pemula','pemulia','pemupuk','pemurah','pemuras','pemusik','pemutar','pemutih','pemutus'),
		'pen'	=> array('pena','penak','penala','penari','penat','penata','penatu','pencak','pencar','pencet','pencil','penda','pendam','pendar','pendek','penemu','pengap','pengki','pening','penipu','peniru','penis','peniti','pensi','pensil','pentas','pentol','penuai','penuh','penyek','penyet','penyok','penyu'),
		'penge'	=> array('pengerat'),
		'peny'	=> array('penyek','penyet','penyok','penyu',),
		'post' => array('poster','postur'),
		'anti' => array('antik','anting'),
		'multi' => array('multiple'),
		'makro' => array('makros'),
		'mikro' => array('mikroba'),
	);
?>
